#!/usr/bin/env bash
# Regenerate the always-on instincts index block in AGENTS.md (mirrored to CLAUDE.md).
#
# Scans the project tier (<root>/.instincts/*.md) and the user tier (~/.instincts/*.md),
# reads each instinct's `name` + `when` from frontmatter, and rewrites a lightweight table
# between the markers below. Progressive disclosure: only this index lives in the agent
# file — never the full rules.
#
# Usage: scripts/index.sh [repo-root]   (defaults to the current directory)
set -euo pipefail

root="${1:-.}"
start="<!-- instincts:index:start -->"
end="<!-- instincts:index:end -->"

emit_rows() {
  local tier="$1" dir="$2" f name when
  [ -d "$dir" ] || return 0
  shopt -s nullglob
  for f in "$dir"/*.md; do
    name=$(awk -F': *' '/^name:/{print $2; exit}' "$f")
    when=$(awk -F': *' '/^when:/{print $2; exit}' "$f")
    [ -n "$name" ] || name=$(basename "$f" .md)
    printf '| %s | %s | %s | %s |\n' "$name" "${when:-—}" "$f" "$tier"
  done
}

block=$(mktemp)
{
  echo "$start"
  echo "<!-- Generated by the instincts skill — do not edit by hand. Open the relevant instinct before coding. -->"
  echo "| instinct | when relevant | path | tier |"
  echo "| --- | --- | --- | --- |"
  emit_rows project "$root/.instincts"
  emit_rows user "$HOME/.instincts"
  echo "$end"
} > "$block"

write_into() {
  local file="$1"
  [ -f "$file" ] || return 0
  if grep -qF "$start" "$file"; then
    awk -v s="$start" -v e="$end" -v b="$block" '
      function print_block(){ while((getline line < b) > 0) print line; close(b) }
      $0 ~ s {print_block(); skip=1; next}
      skip && $0 ~ e {skip=0; next}
      !skip {print}
    ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  else
    { echo; echo "## Instincts"; cat "$block"; } >> "$file"
  fi
  echo "updated $file"
}

write_into "$root/AGENTS.md"
write_into "$root/CLAUDE.md"
rm -f "$block"
